# Generated by Django 4.1.7 on 2023-02-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name_plural': 'Скидки'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name_plural': 'Предметы'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Покупки'},
        ),
        migrations.AlterModelOptions(
            name='tax',
            options={'verbose_name_plural': 'Налоги'},
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.CharField(choices=[('USD', 'Dollars'), ('EUR', 'Euros')], default='USD', max_length=3),
        ),
    ]
