# Generated by Django 4.1.7 on 2023-02-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_order_discount_alter_order_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
