# Generated by Django 4.1.7 on 2023-02-17 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_discount_coupon_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tax',
        ),
        migrations.DeleteModel(
            name='Tax',
        ),
    ]
